### ISSUE TITLE
Cannot clone this repo.

### ISSUE THREAD

**Issue by tsheargit** [jprichardson/talks-ncc3-demo#2]
I issued the following  git command to clone this repo but it failed:

> git clone https://github.com/jprichardson/talks-ncc3-demo.git

error: Could not resolve host: github.com; Unknown error while accessing https://github.com/jprichardson/talks-ncc3-demo.git/info/refs?service=git-upload-pack
fatal: HTTP request failed

**Comment by jprichardson** [comment]
Sounds like a github issue? Please reopen if you don't think it is.
